server:
  port: 8090
logging:
  level:
    sql: debug

spring:
  mvc:
    favicon:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url:jdbc: postgresql://localhost:5432/postgres
    username: postgres
    password: sinu
