package com.lotus.uccp.authentication.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.lotus.uccp.util.Constant;

/**
 * Constraint generated by hbm2java
 */
@Entity
@Table(name = "constraint", schema = Constant.SCHEMA )
public class Constraint implements java.io.Serializable {

	private BigDecimal attributeconstraintid;
	private String attributename;
	private String attributevalue;
	private String accessconstrainttype;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;
	private Set<ControlObject> controlObjects = new HashSet<ControlObject>(0);

	public Constraint() {
		 
	}

	public Constraint(BigDecimal attributeconstraintid, String attributename, String attributevalue,
			String accessconstrainttype) {
		this.attributeconstraintid = attributeconstraintid;
		this.attributename = attributename;
		this.attributevalue = attributevalue;
		this.accessconstrainttype = accessconstrainttype;
	}

	public Constraint(BigDecimal attributeconstraintid, String attributename, String attributevalue,
			String accessconstrainttype, String createdby, Date createdon, String lastupdatedby, Date lastupdatedon,
			Set<ControlObject> controlObjects) {
		this.attributeconstraintid = attributeconstraintid;
		this.attributename = attributename;
		this.attributevalue = attributevalue;
		this.accessconstrainttype = accessconstrainttype;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
		this.controlObjects = controlObjects;
	}

	
	@Id
	@SequenceGenerator(name = "constraintSeq", sequenceName = "constraintSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="constraintSeq")
	@Column(name = "attributeconstraintid", unique = true, nullable = false, scale = 0)
	public BigDecimal getAttributeconstraintid() {
		return this.attributeconstraintid;
	}

	public void setAttributeconstraintid(BigDecimal attributeconstraintid) {
		this.attributeconstraintid = attributeconstraintid;
	}

	@Column(name = "attributename", nullable = false, length = 30)
	public String getAttributename() {
		return this.attributename;
	}

	public void setAttributename(String attributename) {
		this.attributename = attributename;
	}

	@Column(name = "attributevalue", nullable = false, length = 100)
	public String getAttributevalue() {
		return this.attributevalue;
	}

	public void setAttributevalue(String attributevalue) {
		this.attributevalue = attributevalue;
	}

	@Column(name = "accessconstrainttype", nullable = false, length = 10)
	public String getAccessconstrainttype() {
		return this.accessconstrainttype;
	}

	public void setAccessconstrainttype(String accessconstrainttype) {
		this.accessconstrainttype = accessconstrainttype;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "constraint")
	public Set<ControlObject> getControlObjects() {
		return this.controlObjects;
	}

	public void setControlObjects(Set<ControlObject> controlObjects) {
		this.controlObjects = controlObjects;
	}

}
