package com.lotus.uccp.authentication.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.lotus.uccp.util.Constant;
/**
 * ConsentGroup generated by hbm2java
 */
@Entity
@Table(name = "consentgroup", schema = Constant.SCHEMA )
public class ConsentGroup implements java.io.Serializable {

	private BigDecimal consentgroupid;
	private String description;
	private String name;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;
	private Set<ConsentGroupTxn> consentGroupTxns = new HashSet<ConsentGroupTxn>(0);
	private Set<ConsentException> consentExceptions = new HashSet<ConsentException>(0);

	public ConsentGroup() {
	}

	public ConsentGroup(BigDecimal consentgroupid) {
		this.consentgroupid = consentgroupid;
	}

	public ConsentGroup(BigDecimal consentgroupid, String description, String name, String createdby,
			Date createdon, String lastupdatedby, Date lastupdatedon, Set<ConsentGroupTxn> consentGroupTxns,
			Set<ConsentException> consentExceptions) {
		this.consentgroupid = consentgroupid;
		this.description = description;
		this.name = name;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
		this.consentGroupTxns = consentGroupTxns;
		this.consentExceptions = consentExceptions;
	}

	@Id
	@SequenceGenerator(name = "consentGrpSeq", sequenceName = "consentGrpSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="consentGrpSeq")	
	@Column(name = "consentgroupid", unique = true, nullable = false, scale = 0)
	public BigDecimal getConsentgroupid() {
		return this.consentgroupid;
	}

	public void setConsentgroupid(BigDecimal consentgroupid) {
		this.consentgroupid = consentgroupid;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", length = 512)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consentGroup")
	public Set<ConsentGroupTxn> getConsentGroupTxns() {
		return this.consentGroupTxns;
	}

	public void setConsentGroupTxns(Set<ConsentGroupTxn> consentGroupTxns) {
		this.consentGroupTxns = consentGroupTxns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consentGroup")
	public Set<ConsentException> getConsentExceptions() {
		return this.consentExceptions;
	}

	public void setConsentExceptions(Set<ConsentException> consentExceptions) {
		this.consentExceptions = consentExceptions;
	}

}
