package com.lotus.uccp.authentication.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.lotus.uccp.util.Constant;

/**
 * ConsentGroupTxn generated by hbm2java
 */
@Entity
@Table(name = "consentgrouptxn", schema = Constant.SCHEMA )
public class ConsentGroupTxn implements java.io.Serializable {

	private BigDecimal consentgrouptxnid;
	private Transaction transaction;
	private ConsentGroup cosdconsentgroup;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;

	public ConsentGroupTxn() {
	}

	public ConsentGroupTxn(BigDecimal consentgrouptxnid, Transaction transaction,
			ConsentGroup cosdconsentgroup) {
		this.consentgrouptxnid = consentgrouptxnid;
		this.transaction = transaction;
		this.cosdconsentgroup = cosdconsentgroup;
	}

	public ConsentGroupTxn(BigDecimal consentgrouptxnid, Transaction transaction,
			ConsentGroup cosdconsentgroup, String createdby, Date createdon, String lastupdatedby,
			Date lastupdatedon) {
		this.consentgrouptxnid = consentgrouptxnid;
		this.transaction = transaction;
		this.cosdconsentgroup = cosdconsentgroup;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
	}

	@Id
	@SequenceGenerator(name = "consentGrpTxnSeq", sequenceName = "consentGrpTxnSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="consentGrpTxnSeq")	
	@Column(name = "consentgrouptxnid", unique = true, nullable = false, scale = 0)
	public BigDecimal getConsentgrouptxnid() {
		return this.consentgrouptxnid;
	}

	public void setConsentgrouptxnid(BigDecimal consentgrouptxnid) {
		this.consentgrouptxnid = consentgrouptxnid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transactionid", nullable = false)
	public Transaction getTransaction() {
		return this.transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consentgroupid", nullable = false)
	public ConsentGroup getConsentGroup() {
		return this.cosdconsentgroup;
	}

	public void setConsentGroup(ConsentGroup cosdconsentgroup) {
		this.cosdconsentgroup = cosdconsentgroup;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

}
