package com.lotus.uccp.authentication.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import com.lotus.uccp.util.Constant;

/**
 * ControlObject generated by hbm2java
 */
@Entity
@Table(name = "controlobject", schema = Constant.SCHEMA)
public class ControlObject implements java.io.Serializable {
	         
	private BigDecimal controlobjectid;
	private Constraint constraint;
	private ControlGroup controlGroup;
	private Transaction transaction;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;

	public ControlObject() {
	}

	public ControlObject(BigDecimal controlobjectid) {
		this.controlobjectid = controlobjectid;
	}

	public ControlObject(BigDecimal controlobjectid, Constraint constraint,
			ControlGroup controlGroup, Transaction transaction, String createdby,
			Date createdon, String lastupdatedby, Date lastupdatedon) {
		this.controlobjectid = controlobjectid;
		this.constraint = constraint;
		this.controlGroup = controlGroup;
		this.transaction = transaction;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
	}

	@Id
	@SequenceGenerator(name = "controlObjectSeq", sequenceName = "controlObjectSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="controlObjectSeq")
	@Column(name = "controlobjectid", unique = true, nullable = false, scale = 0)
	public BigDecimal getControlobjectid() {
		return this.controlobjectid;
	}

	public void setControlobjectid(BigDecimal controlobjectid) {
		this.controlobjectid = controlobjectid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attributeconstraintid")
	public Constraint getConstraint() {
		return this.constraint;
	}

	public void setConstraint(Constraint constraint) {
		this.constraint = constraint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "controlgroupid")
	public ControlGroup getControlGroup() {
		return this.controlGroup;
	}

	public void setControlGroup(ControlGroup controlGroup) {
		this.controlGroup = controlGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transactionid")
	public Transaction getTransaction() {
		return this.transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

}
