package com.lotus.uccp.authentication.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.lotus.uccp.util.Constant;

/**
 * OrganizationUnit generated by hbm2java
 */
@Entity
@Table(name = "organizationunit", schema = Constant.SCHEMA )
public class OrganizationUnit implements java.io.Serializable {

	private BigDecimal organizationUnitid;
	private String businesstypecode;
	private String comments;
	private Date creationdate;
	private BigDecimal defaultprinterid;
	private String name;
	private String recordstatus;
	private String statuscode;
	private String webaddress;
	private String readsid;
	private String maintainsid;
	private String createunitsid;
	private BigDecimal locationid;
	private String uppername;
	private String createdby;
	private Date createdon;
	private String lastupdatedby;
	private Date lastupdatedon;
	private Date lastwritten;
	private Set<AuthorizationGroup> authorizationGroups = new HashSet<AuthorizationGroup>(0);

	public OrganizationUnit() {
	}

	public OrganizationUnit(BigDecimal organizationUnitid) {
		this.organizationUnitid = organizationUnitid;
	}

	public OrganizationUnit(BigDecimal organizationUnitid, String businesstypecode, String comments, Date creationdate,
			BigDecimal defaultprinterid, String name, String recordstatus, String statuscode, String webaddress,
			String readsid, String maintainsid, String createunitsid, BigDecimal locationid, String uppername,
			String createdby, Date createdon, String lastupdatedby, Date lastupdatedon, Date lastwritten,
			Set<AuthorizationGroup> authorizationGroups) {
		this.organizationUnitid = organizationUnitid;
		this.businesstypecode = businesstypecode;
		this.comments = comments;
		this.creationdate = creationdate;
		this.defaultprinterid = defaultprinterid;
		this.name = name;
		this.recordstatus = recordstatus;
		this.statuscode = statuscode;
		this.webaddress = webaddress;
		this.readsid = readsid;
		this.maintainsid = maintainsid;
		this.createunitsid = createunitsid;
		this.locationid = locationid;
		this.uppername = uppername;
		this.createdby = createdby;
		this.createdon = createdon;
		this.lastupdatedby = lastupdatedby;
		this.lastupdatedon = lastupdatedon;
		this.lastwritten = lastwritten;
		this.authorizationGroups = authorizationGroups;
	}

	@Id
	@SequenceGenerator(name = "OrganizationUnitSeq", sequenceName = "OrganizationUnitSeq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="OrganizationUnitSeq")
	@Column(name = "organizationUnitid", unique = true, nullable = false, scale = 0)
	public BigDecimal getorganizationUnitid() {
		return this.organizationUnitid;
	}

	public void setorganizationUnitid(BigDecimal organizationUnitid) {
		this.organizationUnitid = organizationUnitid;
	}

	@Column(name = "businesstypecode", length = 10)
	public String getBusinesstypecode() {
		return this.businesstypecode;
	}

	public void setBusinesstypecode(String businesstypecode) {
		this.businesstypecode = businesstypecode;
	}

	@Column(name = "comments", length = 300)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creationdate", length = 13)
	public Date getCreationdate() {
		return this.creationdate;
	}

	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	@Column(name = "defaultprinterid", scale = 0)
	public BigDecimal getDefaultprinterid() {
		return this.defaultprinterid;
	}

	public void setDefaultprinterid(BigDecimal defaultprinterid) {
		this.defaultprinterid = defaultprinterid;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "recordstatus", length = 10)
	public String getRecordstatus() {
		return this.recordstatus;
	}

	public void setRecordstatus(String recordstatus) {
		this.recordstatus = recordstatus;
	}

	@Column(name = "statuscode", length = 10)
	public String getStatuscode() {
		return this.statuscode;
	}

	public void setStatuscode(String statuscode) {
		this.statuscode = statuscode;
	}

	@Column(name = "webaddress", length = 50)
	public String getWebaddress() {
		return this.webaddress;
	}

	public void setWebaddress(String webaddress) {
		this.webaddress = webaddress;
	}

	@Column(name = "readsid", length = 100)
	public String getReadsid() {
		return this.readsid;
	}

	public void setReadsid(String readsid) {
		this.readsid = readsid;
	}

	@Column(name = "maintainsid", length = 100)
	public String getMaintainsid() {
		return this.maintainsid;
	}

	public void setMaintainsid(String maintainsid) {
		this.maintainsid = maintainsid;
	}

	@Column(name = "createunitsid", length = 100)
	public String getCreateunitsid() {
		return this.createunitsid;
	}

	public void setCreateunitsid(String createunitsid) {
		this.createunitsid = createunitsid;
	}

	@Column(name = "locationid", scale = 0)
	public BigDecimal getLocationid() {
		return this.locationid;
	}

	public void setLocationid(BigDecimal locationid) {
		this.locationid = locationid;
	}

	@Column(name = "uppername", length = 100)
	public String getUppername() {
		return this.uppername;
	}

	public void setUppername(String uppername) {
		this.uppername = uppername;
	}

	@Column(name = "createdby", length = 64)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "lastupdatedby", length = 64)
	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastupdatedon", length = 13)
	public Date getLastupdatedon() {
		return this.lastupdatedon;
	}

	public void setLastupdatedon(Date lastupdatedon) {
		this.lastupdatedon = lastupdatedon;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastwritten", length = 13)
	public Date getLastwritten() {
		return this.lastwritten;
	}

	public void setLastwritten(Date lastwritten) {
		this.lastwritten = lastwritten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationUnit")
	public Set<AuthorizationGroup> getAuthorizationGroups() {
		return this.authorizationGroups;
	}

	public void setAuthorizationGroups(Set<AuthorizationGroup> authorizationGroups) {
		this.authorizationGroups = authorizationGroups;
	}
}
